# Generated by Django 3.2.8 on 2022-03-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='sais',
        ),
    ]
