# Generated by Django 3.2.8 on 2022-03-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sai', '0009_rename_user_sai_userconnection'),
        ('pool', '0002_remove_pool_sais'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='sais',
            field=models.ManyToManyField(related_name='sais_pools', to='sai.Sai'),
        ),
    ]
