# Generated by Django 3.2.8 on 2022-04-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_alter_host_sais'),
        ('group', '0002_group_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_child', to='host.host')),
                ('cod_father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_father', to='host.host')),
            ],
            options={
                'db_table': 'DEPENDENCE',
            },
        ),
    ]
