# Generated by Django 3.2.8 on 2022-04-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_dependence_finished_father'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dependence',
        ),
    ]
