# Generated by Django 3.2.8 on 2022-02-28 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sai', '0002_auto_20220225_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='sai',
            name='mac',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
