# Generated by Django 3.2.8 on 2022-03-02 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sai', '0003_sai_mac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sai',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='sai',
            name='type',
        ),
        migrations.AddField(
            model_name='sai',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sai', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sai',
            name='protocol',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
