# Generated by Django 3.2.8 on 2022-03-02 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sai', '0004_auto_20220302_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sai',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sai', to='user.user'),
            preserve_default=False,
        ),
    ]
