# Generated by Django 3.2.8 on 2022-03-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sai', '0005_alter_sai_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sai',
            name='admin',
        ),
    ]
