# Generated by Django 3.2.8 on 2022-03-02 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sai', '0006_remove_sai_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sai',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sai', to='user.user'),
            preserve_default=False,
        ),
    ]
