# Generated by Django 3.2.8 on 2022-03-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sai', '0008_alter_sai_administrator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sai',
            old_name='user',
            new_name='userConnection',
        ),
    ]
