# Generated by Django 3.2.8 on 2022-03-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_rename_sais_host_sais_hosts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='sais_hosts',
            new_name='sais',
        ),
    ]
