# Generated by Django 3.2.8 on 2022-04-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0011_auto_20220412_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='sais',
        ),
        migrations.DeleteModel(
            name='HostSai',
        ),
    ]
