# Generated by Django 3.2.8 on 2022-04-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0013_auto_20220412_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_father',models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_father',to='host.host')),
                ('cod_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_child', to='host.host')),
                ('finished_child', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'DEPENDENCE',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='host_host',
            field=models.ManyToManyField(blank=True, related_name='hostFather_hostChild', through='host.Dependence', to='host.Host'),
        ),
    ]
