# Generated by Django 3.2.8 on 2022-06-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0014_auto_20220412_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependence',
            name='finished_father',
            field=models.BooleanField(null=True),
        ),
    ]
